language: android
android:
  components:
    - add-on
    - extra
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-27

env:
  global:
    - MALLOC_ARENA_MAX=2

sudo: required

before_install:
  - yes | sdkmanager "platforms;android-27"
  - nvm install 8

install:
  - npm install

script:
  - cd android && ./gradlew assembleRelease

deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
      - farkasantal.hun@gmail.com
    on_success: always
    on_failure: always